export default {
  SIGNUP_USER: 'SIGNUP_USER',
  GET_USER: 'GET_USER',
  LOGIN_USER: 'LOGIN_USER',
  LOGIN_USER_FAILURE: 'LOGIN_USER_FAILURE',
  LOGOUT_USER: 'LOGOUT_USER',
  SETUP_USER: 'SETUP_USER',
  USER_SIGNUP_FAILURE: 'USER_SIGNUP_FAILURE',
  USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE',

  INIT_USERS: 'INIT_USERS',
  INIT_ALL_USERS: 'INIT_ALL_USERS',
  DISPLAY_USER: 'DISPLAY_USER',
  GET_USERS: 'GET_USERS',

  SEARCH_ALL_USERS: 'SEARCH_ALL_USERS',
  SEARCH_ALL_DOCUMENTS: 'SEARCH_ALL_DOCUMENTS',
  SET_SELECTED_USER: 'SET_SELECTED_USER',
  EDIT_USER: 'EDIT_USER',
  DELETE_USER: 'DELETE_USER',

  LOAD_DOCUMENT: 'LOAD_DOCUMENT',
  CREATE_DOCUMENT: 'CREATE_DOCUMENT',
  EDIT_DOCUMENT: 'EDIT_DOCUMENT',
  SETUP_DOCUMENT: 'SETUP_DOCUMENT',
  DELETE_DOCUMENT: 'DELETE_DOCUMENT',
  DISPLAY_DOCUMENT: 'DISPLAY_DOCUMENT',

  LOAD_ROLE: 'LOAD_ROLE',
  SETUP_ROLE: 'SET_ROLE',
  DELETE_ROLE: 'DELETE_CURRENT_ROLE'
};
